version: '3.9'

services:
  db:
    image: registry.dev-1.uspenskiy.su:443/votingapp/db:latest
    build: ./infra/database/Dockerfile
    hostname: db
    restart: always
    networks:
      - VotingAppNetwork
    volumes:
      - "votingapp-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD_FILE=/run/secrets/PostgresPassword
      - KEYCLOAK_DB_USER=keycloak
      - KEYCLOAK_DB_NAME=keycloak_db
      - VOTINGAPP_DB_USER=votingapp
      - VOTINGAPP_DB_NAME=votingapp_db
    secrets:
      - PostgresPassword
      - PostgresKeycloakPassword
      - PostgresVotingAppPassword

  keycloak:
    image: registry.dev-1.uspenskiy.su:443/votingapp/keycloak:latest
    build: ./infra/keycloak/Dockerfile
    hostname: keycloak
    restart: always
    ports:
      - 7001:8080
    networks:
      - VotingAppNetwork
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD_FILE=/run/secrets/KeycloakAdminPassword
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak_db
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD_FILE=/run/secrets/PostgresPassword
      - KEYCLOAK_DATABASE_SCHEMA=public
    secrets:
      - KeycloakAdminPassword
      - PostgresPassword

  frontend:
    image: registry.dev-1.uspenskiy.su:443/votingapp/frontend:latest
    build: ./frontend/Dockerfile
    hostname: frontend
    restart: always
    ports:
      - 7002:80
    networks:
      - VotingAppNetwork
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=7003

  backend:
    image: registry.dev-1.uspenskiy.su:443/votingapp/backend:latest
    build: ./backend/Dockerfile
    hostname: backend
    restart: always
    ports:
      - 7003:8080
    environment:
      - DATABASE_PASSWORD_FILE=/run/secrets/PostgresVotingAppPassword
    networks:
      - VotingAppNetwork
    configs:
      - source: VotingAppBackendConfig
        target: /app/appsettings.json
    secrets:
      - PostgresVotingAppPassword

networks:
  VotingAppNetwork:

volumes:
  votingapp-data:
    external: true

secrets:
  PostgresPassword:
    external: true
  PostgresKeycloakPassword:
    external: true
  PostgresVotingAppPassword:
    external: true

  KeycloakAdminPassword:
    external: true

configs:
  VotingAppBackendConfig:
    external: true