#!/bin/bash
set -e

export KEYCLOAK_DB_PASSWORD=$(cat /run/secrets/PostgresKeycloakPassword)
export VOTINGAPP_DB_PASSWORD=$(cat /run/secrets/PostgresVotingAppPassword)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER $KEYCLOAK_DB_USER WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
	CREATE DATABASE $KEYCLOAK_DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB_NAME TO $KEYCLOAK_DB_USER;

    CREATE USER $VOTINGAPP_DB_USER WITH PASSWORD '$VOTINGAPP_DB_USER';
	CREATE DATABASE $VOTINGAPP_DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $VOTINGAPP_DB_NAME TO $VOTINGAPP_DB_USER;
EOSQL