name: Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Move to backend project
        run: cd backend
      -
        name: Get version
        id: versioner
        run: echo version=$(awk -F '[<>]' '/Version/{print $3}' VotingApp.Web/VotingApp.Web.csproj | head -n 1) >> $GITHUB_OUTPUT
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      -
        name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      -
        name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push to local registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.CONTAINER_REGISTRY }}/votingapp/backend:${{ steps.parser.outputs.version }},${{ vars.CONTAINER_REGISTRY }}/votingapp/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max